### ISSUE TITLE
If the directory permissions is 777, CD command is optional, the color is not friendly, too ugly, is there any way?

### ISSUE THREAD

**Issue by wpecker** [joel-porquet/zsh-dircolors-solarized#6]
If the directory permissions is 777, CD command is optional, the color is not friendly, too ugly, is there any way?

![image](https://user-images.githubusercontent.com/6280121/34867540-6f3ba496-f7bb-11e7-9340-764d8955edba.png)

**Comment by joel-porquet** [comment]
I don't know any other way. Maybe avoid having 777 directories?
