### ISSUE TITLE
Not supported on Mac OSX

### ISSUE THREAD

**Issue by StrongJoshua** [joel-porquet/zsh-dircolors-solarized#9]
Since the command `dircolors` does not exist on Mac OSX, it is impossible to run the set up script. Apparently `gdircolors`, as provided through brew's `core-utils` plugin is the OSX equivalent.

Would it be possible to make this plugin be supported on Mac OSX?

**Comment by joel-porquet** [comment]
Let me look into that sometime soon.

**Comment by joel-porquet** [comment]
Could you maybe alias `dircolors` to `gdircolors` in your ZSH config? It would probably work fine.

**Comment by StrongJoshua** [comment]
I can confirm that worked after installing coreutils.

**Comment by joel-porquet** [comment]
Resolved.
